FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Au lieu de COPY . .
COPY src/ ./src
COPY public/ ./public
COPY index.js jest.config.js jsconfig.json ./


EXPOSE 3000

CMD [ "npm", "start" ]